name: Scala CI

on:
  push:
    branches: [ master, build_sbt ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala 
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test
    - name: Scalafix
      run: sbt "scalafixAll --rules ProcedureSyntax --check"
