name: Scala CI

on: [push]

jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Build and Test
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      run: sbt -v -Dfile.encoding=UTF-8 +test

  Scalafix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - name: Scalafix
      env:
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      run: sbt "scalafix --check --rules RemoveUnused NoAutoTupling NoValInForComprehension DisableSyntax ProcedureSyntax LeakingImplicitClassVal"

